package store;

import java.awt.event.KeyEvent;
import java.io.BufferedOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletResponse;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanisha
 */
public class Billing extends javax.swing.JFrame {
    public int index=0;
    public int Bill1=0;
    public float cost=0;
    
    
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Date = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        custname = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cno = new javax.swing.JLabel();
        cono = new javax.swing.JTextField();
        serach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        BtnBill = new javax.swing.JButton();
        ABC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Date.setText("Date");
        jPanel1.add(Date);
        Date.setBounds(660, 200, 188, 25);
        jPanel1.add(DateChooser);
        DateChooser.setBounds(660, 240, 190, 30);

        custname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        custname.setText("Customer Name");
        jPanel1.add(custname);
        custname.setBounds(660, 280, 199, 25);

        cname.setEnabled(false);
        jPanel1.add(cname);
        cname.setBounds(660, 320, 199, 30);

        cno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cno.setText("Contact Number");
        jPanel1.add(cno);
        cno.setBounds(340, 200, 199, 25);

        cono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                conoFocusLost(evt);
            }
        });
        jPanel1.add(cono);
        cono.setBounds(340, 240, 199, 30);

        serach.setText("jButton1");
        serach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachActionPerformed(evt);
            }
        });
        jPanel1.add(serach);
        serach.setBounds(550, 240, 20, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bar Code", "Product Name", "Qty", "Selling Price", "Discount", "Final Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableFocusLost(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 380, 720, 120);

        BtnBill.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnBill.setText("Bill");
        BtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBill);
        BtnBill.setBounds(550, 550, 60, 30);

        ABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCActionPerformed(evt);
            }
        });
        jPanel1.add(ABC);
        ABC.setBounds(750, 550, 100, 30);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject1/Images/Undo_35px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 250, 650);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 72)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Billing");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 10, 520, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1080, 4, 20, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(250, 110, 860, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1110, 700);

        setSize(new java.awt.Dimension(1103, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void serachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachActionPerformed
        // TODO add your handling code here:
        jdbc a = new jdbc();
        long Co1;
        String query=null;
        
        Co1=Long.parseLong(cono.getText());
        
        try
        {
            query="select a.Name,a.ACId from ac_detail a,ac_type b where a.contact="+Co1+" and a.acid=b.acid and b.actype='Buyer'";
            a.stmt=a.con.prepareStatement(query);
            a.rs=a.stmt.executeQuery();
            if(a.rs.next())
            {
                cname.setText(a.rs.getString("name"));
                index=a.rs.getInt("ACId");
                System.out.println(index);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Data is not present");
                cono.grabFocus();
                cono.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_serachActionPerformed

    private void BtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillActionPerformed
                 
        jdbc a = new jdbc();
        jdbc b = new jdbc();
        String Query,Query1,Query2;
        
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int i=0;
         String Query5,Query6;
            jdbc z=new jdbc();
            jdbc y=new jdbc();
            
       
       
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if(DateChooser == null)
        {
            DateChooser = new com.toedter.calendar.JDateChooser();
        }
        String sd = dateFormat.format(DateChooser.getDate());
        System.out.println(sd);
   
        
        try
        {
            
            Query1="insert sell_bill_detail values(?,?,?)";
            b.stmt=b.con.prepareStatement(Query1);
            b.stmt.setString(1, null);
            b.stmt.setString(2, sd);
            b.stmt.setInt(3,index);
            b.stmt.executeUpdate();
          
                  
            Query2="select max(SBId) as max from sell_bill_detail";
            b.stmt=b.con.prepareStatement(Query2);
            b.rs=b.stmt.executeQuery();
            if(b.rs.next())
            {
                 Bill1=b.rs.getInt("max");
                 System.out.println(Bill1);
            }
            
            Query="insert sell_bill_item_detail values(?,?,?,?,?)";
            a.stmt=a.con.prepareStatement(Query);
            
                   
            while(i<(table.getRowCount()-1))
            {
                a.stmt.setString(1, null);
                a.stmt.setInt(2, Bill1);
                a.stmt.setInt(3, Integer.parseInt(String.valueOf(table.getValueAt(i, 0))));
                a.stmt.setInt(4, Integer.parseInt(String.valueOf(table.getValueAt(i, 2))));
                a.stmt.setFloat(5, Float.parseFloat(String.valueOf(table.getValueAt(i, 5))));
                a.stmt.executeUpdate();
                i++;
            } 
            
               new Bill(Bill1,cost).setVisible(true); 
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_BtnBillActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tableFocusGained

    private void conoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conoFocusLost
    table.grabFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_conoFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         // TODO add your handling code here:
         table.getCellEditor(0, 1);
         Date date = new Date();
         DateChooser.setDate(date);
    }//GEN-LAST:event_formWindowOpened

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
    if(evt.getKeyChar()==KeyEvent.VK_ENTER)
    {
    System.out.println("store.Billing.enter()");
    jdbc a = new jdbc();
    int recordIndex,i=0,flag=0;
    DefaultTableModel tab = (DefaultTableModel) table.getModel();
    
            
    int row = table.getSelectedRow();
    int value = Integer.parseInt(String.valueOf(table.getValueAt(row, 0)));
    //int value = (int) table.getModel().getValueAt(row, 0); //from selected row 0th position
    if(table.getModel().getValueAt(row, 0) != null) {
    //
    
    while(i < tab.getRowCount())
    {
        int x = (int) table.getValueAt(i,0);
        
        if(x==value && table.getValueAt(i,1) != null && !table.getValueAt(i,1).toString().trim().equals(""))
        {
         flag=1;   
         break;
        }
        i++;
    }
    if(flag==1)
    {
        float y1 = 0;
        int x = Integer.parseInt(String.valueOf(table.getValueAt(i,2)));
        x+=1;
        table.setValueAt(x, i,2);
        try
        {
            String q1="select selling_cost from stock where item_code="+value+";";
            a.st = a.con.createStatement();
            a.rs = a.st.executeQuery(q1);
            if(a.rs.next())
            {
               y1=a.rs.getInt("selling_cost");
            }
        }catch(Exception ec)
        {
            
        }
        y1=y1*x;
        table.setValueAt(y1, i, 3);
        int qty = Integer.parseInt(String.valueOf(table.getValueAt(i, 2)));
        float price = Float.parseFloat(String.valueOf(table.getValueAt(i, 3)));
        float discount = Float.parseFloat(String.valueOf(table.getValueAt(i, 4)));
        float x1 = price*(discount/100);
        float rate = price-x1;
        table.setValueAt(rate, i, 5);
        table.setValueAt(null,row,0);
    }        
    }

    if(flag==0)
    {
        
        try
        {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            String q = " select * from inventory where item_code="+value+";";
            a.st = a.con.createStatement();
            a.rs = a.st.executeQuery(q);
            if(a.rs.next())
            {
             table.setValueAt(a.rs.getString("pname"), row, 1);
             table.setValueAt("1", row, 2);
             
            
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No such item is present");
            }
            String q1="select selling_cost from stock where item_code="+value+";";
            a.st = a.con.createStatement();
            a.rs = a.st.executeQuery(q1);
            if(a.rs.next())
            {
               
                table.setValueAt(a.rs.getInt("selling_cost"), row, 3);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Selling Cost is not present");
            }
                
            String q2="select discount from discount where item_code="+value+";";
            a.st = a.con.createStatement();
            a.rs = a.st.executeQuery(q2);
            if(a.rs.next())
            {
                table.setValueAt(a.rs.getInt("discount"), row, 4);
                int qty = Integer.parseInt(String.valueOf(table.getValueAt(row, 2)));
                float price = Float.parseFloat(String.valueOf(table.getValueAt(row, 3)));
                float discount = Float.parseFloat(String.valueOf(table.getValueAt(row, 4)));
                float x1 = qty*price*(discount/100);
                float rate = price-x1;
                cost = (int) (cost+rate);
                ABC.setText(""+cost);
                table.setValueAt(rate, row, 5);
                model.addRow(new Object[]{"", " ", ""});
            }
            else
            {
                 table.setValueAt(0, row, 4);
                int qty = Integer.parseInt(String.valueOf(table.getValueAt(row, 2)));
                float price = Float.parseFloat(String.valueOf(table.getValueAt(row, 3)));
                float discount = Float.parseFloat(String.valueOf(table.getValueAt(row, 4)));
                float x1 = qty*price*(discount/100);
                float rate = price-x1;
                cost = (int) (cost+rate);
                ABC.setText(""+cost);
                table.setValueAt(rate, row, 5);
                model.addRow(new Object[]{"", " ", ""});
            }
            
            
        }
        
        catch(Exception ex)
        {
          JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
}// TODO add your handling code here:
    }//GEN-LAST:event_tableKeyPressed

    private void tableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusLost
        // TODO add your handling code here:
        System.out.println("store.Billing.tableFocusLost()");
    }//GEN-LAST:event_tableFocusLost

    private void ABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABCActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.hide();
        Home frm=new Home();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ABC;
    private javax.swing.JButton BtnBill;
    private javax.swing.JLabel Date;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel cno;
    private javax.swing.JTextField cono;
    private javax.swing.JLabel custname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton serach;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
