/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uttam
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form b
     */
    public Inventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adddata = new javax.swing.JPanel();
        icode = new javax.swing.JTextField();
        itemcode = new javax.swing.JLabel();
        productid = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        productname = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Icode = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Pid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deleteinv = new javax.swing.JPanel();
        delete1 = new javax.swing.JButton();
        Pname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Pid1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Icode1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        item1 = new javax.swing.JTextField();
        ok1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("                                 Add");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 50));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("                                 Delete");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -2, 300, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 50));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("                                 View");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("                                 Edit");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 300, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject1/Images/Undo_35px.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jPanel2.setLayout(new java.awt.CardLayout());

        adddata.setBackground(new java.awt.Color(255, 255, 255));
        adddata.setForeground(new java.awt.Color(255, 51, 102));
        adddata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        adddata.add(icode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 199, -1));

        itemcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemcode.setText("Item Code");
        adddata.add(itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 199, 25));

        productid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productid.setText("Product ID");
        adddata.add(productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 199, 25));
        adddata.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 199, -1));

        productname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productname.setText("Product Name");
        adddata.add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 199, 25));
        adddata.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 199, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        adddata.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel18.setText("Add");
        adddata.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel28.setText("Inventory");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel24))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adddata.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 100));

        jPanel2.add(adddata, "card2");

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_Code", "Product Id", "Product Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(p1);

        view.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 550, 310));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel16.setText("Inventory");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 279, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(241, 241, 241)
                        .addComponent(jLabel26))
                    .addComponent(jSeparator2)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        view.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel14.setText("View");
        view.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jPanel2.add(view, "card4");

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Item Code:");
        edit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 97, 24));

        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMouseClicked(evt);
            }
        });
        edit.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 150, 30));

        jLabel6.setText("Item Code:");
        edit.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 88, 25));

        Icode.setEnabled(false);
        edit.add(Icode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 30));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        edit.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 50, -1));

        jLabel7.setText("Product Id:");
        edit.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 88, 25));

        Pid.setEnabled(false);
        edit.add(Pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, 30));

        jLabel8.setText("Product Name:");
        edit.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 88, 28));

        Pname.setEnabled(false);
        edit.add(Pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 30));

        save.setText("save");
        save.setEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        edit.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 87, 32));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel17.setText("Inventory");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(206, 206, 206)
                .addComponent(jLabel30)
                .addGap(40, 40, 40)
                .addComponent(jLabel25))
            .addComponent(jSeparator4)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        edit.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 100));

        jLabel15.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel15.setText("Edit");
        edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jPanel2.add(edit, "card5");

        deleteinv.setBackground(new java.awt.Color(255, 255, 255));
        deleteinv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete1.setText("Delete");
        delete1.setEnabled(false);
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        deleteinv.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 87, 32));

        Pname1.setEnabled(false);
        deleteinv.add(Pname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 358, 150, 30));

        jLabel10.setText("Product Name:");
        deleteinv.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 88, 28));

        jLabel11.setText("Product Id:");
        deleteinv.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 88, 25));

        Pid1.setEnabled(false);
        deleteinv.add(Pid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 306, 150, 30));

        jLabel12.setText("Item Code:");
        deleteinv.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 88, 25));

        Icode1.setEnabled(false);
        deleteinv.add(Icode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 30));

        jLabel13.setText("Item Code:");
        deleteinv.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 97, 24));

        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        deleteinv.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 148, 24));

        ok1.setText("OK");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        deleteinv.add(ok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel20.setText("Delete");
        deleteinv.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel19.setText("Inventory");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 314, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(226, 226, 226)
                .addComponent(jLabel29)
                .addGap(40, 40, 40)
                .addComponent(jLabel22))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        deleteinv.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 100));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_20px.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        deleteinv.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        deleteinv.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 840, 20));

        jPanel2.add(deleteinv, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        deleteinv.setVisible(false);
        adddata.setVisible(true);
        view.setVisible(false);
        edit.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        deleteinv.setVisible(true);
        adddata.setVisible(false);
        view.setVisible(false);
        edit.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        deleteinv.setVisible(false);
        adddata.setVisible(false);
        view.setVisible(true);
        edit.setVisible(false);        // TODO add your handling code here:
        jdbc j=new jdbc();     
       
         DefaultTableModel model=(DefaultTableModel)p1.getModel();
        
        while(p1.getRowCount()>0)
        {
            model.removeRow(0);
        }
        try
        {
        String query="select * from Inventory";
        j.rs=j.st.executeQuery(query);
        while(j.rs.next())
        {
                    int d1=j.rs.getInt("Item_code");
                    String d2=j.rs.getString("Pid");
                    String d3=j.rs.getString("Pname");
                    
                    model.addRow(new Object[]{d1,d2,d3});
        }
        
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        deleteinv.setVisible(false);
        adddata.setVisible(false);
        view.setVisible(false);
        edit.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String query=null;
        jdbc a = new jdbc();
        int Icode;
        String PName,Pcode;
        Icode=Integer.parseInt(icode.getText());
        Pcode=pid.getText();
        PName=pname.getText();
        try
        {
            query="insert into inventory(Item_code,PId,Pname) values(?,?,?);";
            a.stmt=a.con.prepareStatement(query);
            a.stmt.setInt(1,Icode);
            a.stmt.setString(2,Pcode);
            a.stmt.setString(3,PName);

            int i= a.stmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null,"Data is save");
                icode.setText("");
                pid.setText("");
                pname.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "data is  not saved");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_addActionPerformed

    private void itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseClicked
        // TODO add your handling code here:
        item.setText("");
    }//GEN-LAST:event_itemMouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        jdbc j=new jdbc();
        String query;
        int i1;

        i1=Integer.parseInt(item.getText());

        try
        {
            query="select * from inventory where Item_code="+i1+"";
            j.stmt=j.con.prepareStatement(query);
            j.rs=j.stmt.executeQuery();
            if(j.rs.next())
            {
                Icode.setText(""+j.rs.getInt("Item_code"));
                Pid.setText(j.rs.getString("PId"));
                Pname.setText(j.rs.getString("Pname"));

                Icode.setEnabled(true);
                Pid.setEnabled(true);
                Pname.setEnabled(true);
                save.setEnabled(true);
            }

            else
            {
                JOptionPane.showMessageDialog(null,"No data present");
                item.setText("");
                item.grabFocus();

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_okActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        jdbc a=new jdbc();
        String query,P2,P1;
        int I1,I2;

        P2=Pname.getText();
        P1=Pid.getText();
        I1=Integer.parseInt(Icode.getText());
        I2=Integer.parseInt(item.getText());
        try
        {
            query="update Inventory set Item_code="+I1+",Pid='"+P1+"',Pname='"+P2+"' where Item_code="+I2+"";
            a.stmt=a.con.prepareStatement(query);
            int i=a.stmt.executeUpdate(query);
            if(i>0)
            {
                JOptionPane.showMessageDialog(null,"Update Successfully");
         
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error in Update");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        jdbc a=new jdbc();
        String query;
        int I2;

        I2=Integer.parseInt(item1.getText());
        try
        {
            query="delete from Inventory where Item_code="+I2+"";
            a.stmt=a.con.prepareStatement(query);
            int i=a.stmt.executeUpdate(query);
            if(i>0)
            {
                JOptionPane.showMessageDialog(null,"Delete Successfully");
              
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error in Delete");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
        item.setText("");
    }//GEN-LAST:event_item1MouseClicked

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        // TODO add your handling code here:
        jdbc j=new jdbc();
        String query;
        int i1;

        i1=Integer.parseInt(item1.getText());

        try
        {
            query="select * from inventory where Item_code="+i1+"";
            j.stmt=j.con.prepareStatement(query);
            j.rs=j.stmt.executeQuery();
            if(j.rs.next())
            {
                Icode1.setText(""+j.rs.getInt("Item_code"));
                Pid1.setText(j.rs.getString("PId"));
                Pname1.setText(j.rs.getString("Pname"));
                delete1.setEnabled(true);
            }

            else
            {
                JOptionPane.showMessageDialog(null,"No data present");
                item.setText("");
                item.grabFocus();

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_ok1ActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        this.hide();
        Home frm=new Home();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Icode;
    private javax.swing.JTextField Icode1;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pid1;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField Pname1;
    private javax.swing.JButton add;
    private javax.swing.JPanel adddata;
    private javax.swing.JButton delete1;
    private javax.swing.JPanel deleteinv;
    private javax.swing.JPanel edit;
    private javax.swing.JTextField icode;
    private javax.swing.JTextField item;
    private javax.swing.JTextField item1;
    private javax.swing.JLabel itemcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JTable p1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JLabel productid;
    private javax.swing.JLabel productname;
    private javax.swing.JButton save;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
